# /etc/nginx/sites-available/bpsd9.conf
#
# TLS terminates at the AWS ALB; nginx serves plain HTTP on :80.

passenger_ruby /opt/rbenv/shims/ruby;

server {
    listen 80;

    server_name ~^((assets|www)|production\.internal)\.bpsd9\.org$;

    root /var/www/bpsd9/current/public;

    passenger_enabled on;
    rails_env production;
}

server {
    listen 80;

    server_name ~^(assets\.)?staging\.(internal\.)?bpsd9\.org$;

    root /var/www/bpsd9/current/public;

    passenger_enabled on;
    rails_env staging;
}

server {
    listen 80 default_server;

    server_name _;

    location /health-check {
        access_log off;
        return 200;
        add_header Content-Type text/plain;
    }
}
